### ISSUE TITLE
Playing media player toggle rendered as "off"

### ISSUE THREAD

**Issue by jose1711** [house-of-abbey/GarminHomeAssistant#130] opened 2024-03-29 21:17 UTC
My menu item goes like this:
```
    {
     "entity": "media_player.ht_a5000",
     "name": "🔈 Soundbar",
     "type": "toggle"
    }
```

The issue is that during the playback the state is "playing" (not "on"). I believe the application is only checking on/off values in `HomeAssistantToggleMenuItem.mc`. Would it be possible to handle this more like HA does? Thank you.

**Comment by philipabbey** [comment] 2024-03-30 12:16
Thank you for your interest. I will remove the bug label since this is not a bug in the slightest!

Please try using a ["Template" menu item](https://github.com/house-of-abbey/GarminHomeAssistant/blob/main/examples/Templates.md) for things that are not as simple as on-off like lights and switches. You should be able to decode the states as you would prefer.

I'll close this issue in 48 hours if there are no further replies.

**Comment by jose1711** [comment] 2024-03-30 12:25
Thank you. Does that mean that toggle item only can be used with states objects that return on or off?

**Comment by philipabbey** [comment] 2024-03-30 13:28
Yes. The API call must return "on" or "off" see these two points in the code:
- https://github.com/house-of-abbey/GarminHomeAssistant/blob/main/source/HomeAssistantToggleMenuItem.mc#L120
- https://github.com/house-of-abbey/GarminHomeAssistant/blob/main/source/HomeAssistantToggleMenuItem.mc#L45

The set state API call must use `turn_on` and `turn_off`:
- https://github.com/house-of-abbey/GarminHomeAssistant/blob/main/source/HomeAssistantToggleMenuItem.mc#L235

Think of a `toggle` as just a specialised `template` for things that are obviously on-off, e.g. covers can be ambiguous here (open/closed - which is green for on?) Its just the template requires a little more work, but the user can get what they precisely need.

**Comment by jose1711** [comment] 2024-03-31 20:38
Thank you for the explanation. To be able to "emulate" a standard toggle using template, I am missing an option to set an icon. Template icon - unlike toggle - seems to only support static icon. Is there a chance to change this?

**Comment by philipabbey** [comment] 2024-03-31 21:09
Garmin Connect IQ does not support the provision of any icons in menu items. The toggle is a special case. I suggest you choose unicode characters to put in a conditional Jinga statement in your template definition.

**Comment by philipabbey** [comment] 2024-04-18 18:00
Closing as the issue has gone stale.

**Closed by philipabbey** 2024-04-18 18:00 UTC
Labels: question
