### ISSUE TITLE
No JSON returned from HTTP request

### ISSUE THREAD

**Issue by andrzejpolis** [house-of-abbey/GarminHomeAssistant#161] opened 2024-07-30 10:47 UTC
**Describe the bug**
After doing all steps application doesn't work if on my phone wifi is turned on and connected. It displays message "No JSON returned from HTTP request".  In glances it displays Unavailable for both API and Menu.

File is properly hosted from Home Assistant self hosted installation. I can reach it from my phone and any other device also outside of my local network. My HA installation is reachable through owned domain and has a valid certificate. 

In short:
| Network | Garmin | iPhone access to json file |
| --- | --- | --- |
| Wifi | doesn't work | works |
| Celular | works | works |

**IMPORTANT!**
I have:

- [x] Used HTTPS to access HomeAssistant (with a public certificate)
- [x] Checked that my JSON Syntax is correct ([options 4](https://github.com/house-of-abbey/GarminHomeAssistant#editing-the-json-file) or otherwise)
- [x] Checked that my JSON follows the schema ([options 4](https://github.com/house-of-abbey/GarminHomeAssistant#editing-the-json-file))
- [ ] Used the online editor to check my JSON against HomeAssistant ([option 1](https://github.com/house-of-abbey/GarminHomeAssistant#editing-the-json-file))
- [x] Checked the [Docs](https://github.com/house-of-abbey/GarminHomeAssistant)
- [x] Checked the [Troubleshooting Guide](https://github.com/house-of-abbey/GarminHomeAssistant/blob/main/TroubleShooting.md)

**To Reproduce**

1. Go to application
2. See error "No JSON returned from HTTP request"

**Expected behavior**
Not see error "No JSON returned from HTTP request"

**Garmin Device (please complete the following information):**
Fenix 7

**Smartphone (please complete the following information):**

- Device: iPhone 12 Pro Max
- OS: 17.5.1

**Comment by andrzejpolis** [comment] 2024-07-30 20:46
It was an issue with wifi configuration on watch. Realized that when noticed it all works fine when watch is not in my wifi range. Removing wifi through Connect app and adding it again fixed the problem.

**Comment by philipabbey** [comment] 2024-08-09 09:03
Any chance this is related to the following observations? See https://community.home-assistant.io/t/home-assistant-app-for-garmin/637348/144

**Comment by philipabbey** [comment] 2024-08-09 11:44
Please see https://github.com/house-of-abbey/GarminHomeAssistant/blob/main/README.md#known-issues. This is a bug, but not ours. Its an iPhione ConnectIQ App issue we cannot do anything about as their ConnectIQ it is beyond our control. As such I will close this issue in a few days time unless you can provide more information leading to a bug in our application.

**Comment by andrzejpolis** [comment] 2024-08-09 12:20
I cannot tell if this relates as don't see any indications of similar behavior - that it works on cellular and doesn't on wifi. I'm totally fine with closing this as I made a decision of getting rid off Garmin and stick to my Apple Watch Ultra where I don't have this kind of issues.
Thanks for the support anyway.

**Comment by philipabbey** [comment] 2024-08-09 12:30
> I cannot tell if this relates as don't see any indications of similar behavior - that it works on cellular and doesn't on wifi.

Except the test is not that. The test is whether the Apple ConnectIQ App is open or closed (on Wi-Fi). That the application works on mobile is a sufficient indicator to me there is no bug in the Garmin Application, and the issue is in the network connection beyond the application's control.

**Closed** 2024-08-17 18:08 UTC
Labels: wontfix
