### ISSUE TITLE
display artifacting Garmin instinct 2 tactical

### ISSUE THREAD

**Issue by Nasimovy** [house-of-abbey/GarminHomeAssistant#132] opened 2024-04-05 12:35 UTC
the template and tap functions or entries show artifacts in the smaller screen

I have:

- [X] Used HTTPS to access HomeAssistant (with a public certificate)
- [X] Checked that my JSON Syntax is correct ([options 2, 3, or 4](https://github.com/house-of-abbey/GarminHomeAssistant#editing-the-json-file) or otherwise)
- [X] Checked that my JSON follows the schema ([options 2, 3, or 4](https://github.com/house-of-abbey/GarminHomeAssistant#editing-the-json-file))
- [X] Used the online editor to check my JSON against HomeAssistant ([option 1](https://github.com/house-of-abbey/GarminHomeAssistant#editing-the-json-file))
- [X] Checked the [Docs](https://github.com/house-of-abbey/GarminHomeAssistant)
- [X] Checked the [Troubleshooting Guide](https://github.com/house-of-abbey/GarminHomeAssistant/blob/main/TroubleShooting.md)

**To Reproduce**
1. open the homeassistant app
2. scroll down to template or tap option
3. look at the smaller section of screen

**Expected behavior**
same icon or display as toggle

**Screenshots**
![20240405_143159](https://github.com/house-of-abbey/GarminHomeAssistant/assets/20001575/10a6ad3d-93e3-427a-97ce-f7bd2589d172)
![20240405_143215](https://github.com/house-of-abbey/GarminHomeAssistant/assets/20001575/c09c979a-52a5-4fac-9bf2-d0562f649694)

the toggle shows no artifacting/gibberish
![20240405_143142](https://github.com/house-of-abbey/GarminHomeAssistant/assets/20001575/d9a9087e-34e4-45bf-870c-bfa516845360)

**Garmin Device:**
- Model: instinct 2 tactical

**Smartphone :**
- Device: samsung S21 ultra
- OS: android 14

**Comment by philipabbey** [comment] 2024-04-05 13:18
> To Reproduce
> open the homeassistant app
> scroll down to template or tap option
> Expected behavior: same icon or display as toggle

Sorry I'm a bit lost on this one. The toggle icon is only present for toggle items, not for template ones. For template you have a text string you can form. In there you can include words or unicode (sometimes) characters to display the status of something from your HA instance.

**Comment by Nasimovy** [comment] 2024-04-05 13:21
![image](https://github.com/house-of-abbey/GarminHomeAssistant/assets/20001575/48e335c5-d79e-4996-85bf-6f283764f7a4)
on the toggle option it shows the HA icon

![image](https://github.com/house-of-abbey/GarminHomeAssistant/assets/20001575/0c22f941-047e-4ca5-b57d-78eccb17acbd)
on the tap and template things it shows gibberish/artifacts

**Comment by Nasimovy** [comment] 2024-04-05 13:43
understood, if you want me to do some further testing i will happily do that
its weird that the simulator shows the "smaller screen"inverted
> For now though, I assume the app functions correctly even if it is not pretty?
yes the app is functioning perfectly

**Comment by philipabbey** [comment] 2024-04-05 13:51
From https://developer.garmin.com/connect-iq/reference-guides/devices-reference/, those listed with "Display Colors 2" are:
1. Descent™ G1 / G1 Solar - 176 x 176
2. Edge® 130 - _not supported_
3. Edge® 130 Plus - _not supported_
4. Instinct® 2 / Solar / Dual Power / dēzl Edition - 176 x 176
5. Instinct® 2S / Solar / Dual Power - 163 x 156
6. Instinct® 2X Solar - 176 x 176
7. Instinct® Crossover - 176 x 176

Looks like that list covers just 1 screen sizes. So one new resource folder with black & white bitmap icons is required to fix this.

**Comment by Nasimovy** [comment] 2024-04-05 14:07
would a black and white SVG also work ?
the icon size of the instinct 62x62 do new svgs or bitmaps have to be created for them altogether?

**Comment by philipabbey** [comment] 2024-04-05 14:32
We're already using SVG. We have to make different files anyway, may as well go for a safe option.

**Comment by philipabbey** [comment] 2024-04-05 17:35
There seems to be a fundamental problem here. The same icon file needs to work in two places, each with different sizes.

The following are screenshots from the simulator, hence the rounding of the watch face is missing, you'll have to imagine an overlay.

instinct2 62x62 icons:
![Instinct2](https://github.com/house-of-abbey/GarminHomeAssistant/assets/24634527/6da64439-eac3-4da2-bab2-6067511c225a)

instinct2 simulator window screenshot for comparison to the above:
![image](https://github.com/house-of-abbey/GarminHomeAssistant/assets/24634527/22aecdfa-2b22-417b-a446-9b33efe66f72)

This should show you have the screen layout maps.

instinct2s 54x54 icons:
![Instinct2](https://github.com/house-of-abbey/GarminHomeAssistant/assets/24634527/450c2136-4483-43c6-9328-4ce80aa45303)

instinct2x 62x62 icons:
![instinct2x](https://github.com/house-of-abbey/GarminHomeAssistant/assets/24634527/dd1775cf-12d1-4ee0-beec-1e66a54f7e38)

Instinctcrossover 62x62 icons:
![Instinctcrossover](https://github.com/house-of-abbey/GarminHomeAssistant/assets/24634527/aa48025c-2959-4677-8d0d-bcf1483c9e86)

Now obviously the menu items can't take a 54 or 62 square pixel icon, so the files have been scaled back to 18 and 21 square pixels respectively. They appear to be too big for the space they are required to occupy. The icons looks terrible in both locations and the backgrounds they go onn vary.

The background can be managed by yet another resource directory to invert the colours. I don't know how to manage the need for different sized icons in two places. With the toggle item, the menu item does not have an icon, hence defaults to the application 54/62 pixel icon (I assume). It would be better to use just 54/62 pixel icons in the top right circular window and noen in the menu item. I don't know how to separate that.

**Comment by philipabbey** [comment] 2024-04-05 18:04
Perhaps the answer here is that on the following devices:

1. Descent™ G1 / G1 Solar - 176 x 176
2. Instinct® 2 / Solar / Dual Power / dēzl Edition - 176 x 176
3. Instinct® 2S / Solar / Dual Power - 163 x 156
4. Instinct® 2X Solar - 176 x 176
5. Instinct® Crossover - 176 x 176

the code should use a [`MenuItem`](https://developer.garmin.com/connect-iq/api-docs/Toybox/WatchUi/MenuItem.html) instead of an [`IconMenuItem`](https://developer.garmin.com/connect-iq/api-docs/Toybox/WatchUi/IconMenuItem.html). That means writing code to conditionally alter which of those two menu items is used, and then the icon shown in the window would always be the application icon. This sounds like an awful solution!

Which begs the question, how does the code determine the device? [`partNumber`](https://developer.garmin.com/connect-iq/api-docs/Toybox/System/DeviceSettings.html#partNumber-var)?

**Comment by philipabbey** [comment] 2024-09-07 10:19
I'm closing this issue as the problem is too specific to a few devices and not general. The fix looks involved, so I'm just going to suggest you wait until you upgrade your watch for a newer model. Sorry that's not ideal.

**Closed by philipabbey** 2024-09-07 10:19 UTC
Labels: bug, wontfix
